### ISSUE TITLE
Add the ability to write results of Flink jobs to BigQuery tables 

### ISSUE THREAD

**Issue by Moustafazeinhaat** [GoogleCloudDataproc/flink-bigquery-connector#102]
It's required to use this lib to add the ability to write results of Flink jobs to BigQuery tables

**Comment by jayehwhyehentee** [comment]
We released [0.2.0-preview](https://github.com/GoogleCloudDataproc/flink-bigquery-connector/releases/tag/v0.2.0-preview) today with at-least-once write ability using Flink's Datastream API. Exactly-once and Table API support will be released soon.
